added additional check for lcov file

diff --git a/.github/workflows/sdk.yml b/.github/workflows/sdk.yml
--- a/.github/workflows/sdk.yml
+++ b/.github/workflows/sdk.yml
@@ -56,7 +56,13 @@ jobs:
         run: pnpm run test:unit:coverage
 
       - name: Move the report at the root of the project
-        run: mv coverage/lcov.info .
+        run: |
+          if [ -f coverage/lcov.info ]; then
+            mv coverage/lcov.info .
+          else
+            echo "lcov.info file not found!"
+            exit 1
+          fi
 
       - name: Upload coverage report to Codecov
         uses: codecov/codecov-action@v3
