debugging ccoverage step

diff --git a/.github/workflows/sdk.yml b/.github/workflows/sdk.yml
--- a/.github/workflows/sdk.yml
+++ b/.github/workflows/sdk.yml
@@ -55,10 +55,22 @@ jobs:
       - name: Run the unit tests
         run: pnpm run test:unit:coverage
 
+      - name: List coverage directory
+        run: ls -R coverage
+
+      - name: Move the coverage report to root (if needed)
+        run: |
+          if [ -f coverage/lcov.info ]; then
+            mv coverage/lcov.info .
+          else
+            echo "lcov.info file not found!"
+            exit 1
+          fi
+
       - name: Upload coverage report to Codecov
         uses: codecov/codecov-action@v3
         with:
-          files: ./coverage/lcov.info
+          files: ./lcov.info
           token: ${{ secrets.CODECOV_TOKEN }}
           fail_ci_if_error: true
           verbose: true
